server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

ribbon: 
  eureka: 
    enabled: false


zuul:
  routes:
    department-proxy:
      serviceId: department-service
      path: /department/**
    employee-proxy:
      serviceId: employee-service
      path: /employee/**
    environment-proxy:
      serviceId: environment-service
      path: /environment/**
    organization-proxy:
      serviceId: organization-service
      path: /organization/**

department-proxy:   
  ribbon:
    listOfServers: department

employee-proxy:   
  ribbon:
    listOfServers: employee

environment-proxy:   
  ribbon:
    listOfServers: environment

organization-proxy:   
  ribbon:
    listOfServers: organization

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"