server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

ribbon: 
  eureka: 
    enabled: false


zuul:
  routes:
    department-service:
      url: http://department:8080
    employee-service:
      url: http://employee:8080
    environment-service:
      url: http://environment:8080
    organization-service:
      url: http://organization:8080


logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"