server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway

ribbon: 
  eureka: 
    enabled: false


zuul:
  routes:
    department:
      serviceId: department
      #path: /department/**
    employee:
      serviceId: employee
      #path: /employee/**
    organization:
      serviceId: organization
      #path: /organization/**
    environment:
      serviceId: environment
      #path: /environment/**


logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"