apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: medici/admin
    context: k8s-admin-service
  - image: medici/employee
    context: k8s-employee-service
  - image: medici/department
    context: k8s-department-service
  - image: medici/organization
    context: k8s-organization-service
  - image: medici/gateway
    context: k8s-gateway-service
  - image: medici/manager
    context: k8s-manager-service
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/**.yaml
profiles:
- name: james, dev
  build:
    local:
      push: false