apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: medici/admin
    context: k8s-admin-service
  - image: medici/admin-client
    context: k8s-admin-client-service
  - image: medici/ambassador
    context: k8s-ambassador-service
  - image: medici/employee
    context: k8s-employee-service
  - image: medici/department
    context: k8s-department-service
  - image: medici/organization
    context: k8s-organization-service
  - image: medici/gateway
    context: k8s-gateway-service
  - image: medici/manager
    context: k8s-manager-service
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/mongodb-secret.yaml
    - ./kubernetes/mongodb-deployment.yaml
    - ./kubernetes/mongodb-configmap.yaml
    - ./kubernetes/admin-deployment.yaml
    - ./kubernetes/admin-client-deployment.yaml
    - ./kubernetes/ambassador-deployment.yaml
    - ./kubernetes/department-deployment.yaml
    - ./kubernetes/employee-deployment.yaml
    - ./kubernetes/manager-deployment.yaml
    - ./kubernetes/organization-deployment.yaml
    - ./kubernetes/gateway-deployment.yaml
    - ./kubernetes/ingress.yaml
profiles:
- name: james, dev, kubernetes, mongo
  build:
    local:
      push: false